
name: Build docker image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: build docker
        uses: docker/build-push-action@v1
        with: 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kuozo/cam
          tag_with_ref: true
